apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-deployment
        configMap:
          name: nginx-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-deployment
  namespace: default
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:green;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf </h1>
    </html