apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: ServiceAccount
  name: status-checker 
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: status-checker
  apiGroup: ""