apiVersion: apps/v1
kind: Deployment
metadata:
  name: atpdpd-deployment
  namespace: test22mail-ru
spec:
  selector:
    matchLabels:
      app: atpdpd
  replicas: 1 
  template:
    metadata:
      labels:
        app: atpdpd
    spec:
      containers:
      - name: atpdpd
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: atpdpd-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: atpdpd-deployment
        configMap:
          name: atpdpd-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: atpdpd-service
  namespace: test22mail-ru
spec:
  type: NodePort
  selector:
    app: atpdpd
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: atpdpd-deployment
  namespace: test22mail-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:red;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa5b770fc28d870af1393 of user test22@mail.ru</h1>
    </html