apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktwdih-deployment
  namespace: testgmail-com
spec:
  selector:
    matchLabels:
      app: ktwdih
  replicas: 1 
  template:
    metadata:
      labels:
        app: ktwdih
    spec:
      containers:
      - name: ktwdih
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: ktwdih-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: ktwdih-deployment
        configMap:
          name: ktwdih-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: ktwdih-service
  namespace: testgmail-com
spec:
  type: NodePort
  selector:
    app: ktwdih
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ktwdih-deployment
  namespace: testgmail-com
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:maroon;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa431facc58bac164c9b9 of user test@gmail.com</h1>
    </html