apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapfid-deployment
  namespace: mymy-ru
spec:
  selector:
    matchLabels:
      app: sapfid
  replicas: 1 
  template:
    metadata:
      labels:
        app: sapfid
    spec:
      containers:
      - name: sapfid
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: sapfid-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: sapfid-deployment
        configMap:
          name: sapfid-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: sapfid-service
  namespace: mymy-ru
spec:
  type: NodePort
  selector:
    app: sapfid
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sapfid-deployment
  namespace: mymy-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:lime;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa07f84d836bfea8d5ab4 of user my@my.ru</h1>
    </html