apiVersion: apps/v1
kind: Deployment
metadata:
  name: quqsas-deployment
  namespace: mymy-ru
spec:
  selector:
    matchLabels:
      app: quqsas
  replicas: 1 
  template:
    metadata:
      labels:
        app: quqsas
    spec:
      containers:
      - name: quqsas
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: quqsas-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: quqsas-deployment
        configMap:
          name: quqsas-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: quqsas-service
  namespace: mymy-ru
spec:
  type: NodePort
  selector:
    app: quqsas
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: quqsas-deployment
  namespace: mymy-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:2;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa0580c322f2fc0858f91 of user my@my.ru</h1>
    </html