apiVersion: apps/v1
kind: Deployment
metadata:
  name: trqirh-deployment
  namespace: test22mail-ru
spec:
  selector:
    matchLabels:
      app: trqirh
  replicas: 1 
  template:
    metadata:
      labels:
        app: trqirh
    spec:
      containers:
      - name: trqirh
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: trqirh-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: trqirh-deployment
        configMap:
          name: trqirh-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: trqirh-service
  namespace: test22mail-ru
spec:
  type: NodePort
  selector:
    app: trqirh
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: trqirh-deployment
  namespace: test22mail-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:yellow;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa58570fc28d870af1361 of user test22@mail.ru</h1>
    </html