apiVersion: apps/v1
kind: Deployment
metadata:
  name: jujrag-deployment
  namespace: mymy-ru
spec:
  selector:
    matchLabels:
      app: jujrag
  replicas: 1 
  template:
    metadata:
      labels:
        app: jujrag
    spec:
      containers:
      - name: jujrag
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: jujrag-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: jujrag-deployment
        configMap:
          name: jujrag-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: jujrag-service
  namespace: mymy-ru
spec:
  type: NodePort
  selector:
    app: jujrag
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jujrag-deployment
  namespace: mymy-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:olive;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa30f84d836bfea8d5b43 of user my@my.ru</h1>
    </html