apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffhrdr-deployment
  namespace: mymy-ru
spec:
  selector:
    matchLabels:
      app: ffhrdr
  replicas: 1 
  template:
    metadata:
      labels:
        app: ffhrdr
    spec:
      containers:
      - name: ffhrdr
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: ffhrdr-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: ffhrdr-deployment
        configMap:
          name: ffhrdr-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: ffhrdr-service
  namespace: mymy-ru
spec:
  type: NodePort
  selector:
    app: ffhrdr
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ffhrdr-deployment
  namespace: mymy-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:maroon;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa07184d836bfea8d5aaf of user my@my.ru</h1>
    </html