apiVersion: apps/v1
kind: Deployment
metadata:
  name: eqpksf-deployment
  namespace: sashatest-ru
spec:
  selector:
    matchLabels:
      app: eqpksf
  replicas: 1 
  template:
    metadata:
      labels:
        app: eqpksf
    spec:
      containers:
      - name: eqpksf
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: eqpksf-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: eqpksf-deployment
        configMap:
          name: eqpksf-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: eqpksf-service
  namespace: sashatest-ru
spec:
  type: NodePort
  selector:
    app: eqpksf
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: eqpksf-deployment
  namespace: sashatest-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:black;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa5fb70fc28d870af13ab of user sasha@test.ru</h1>
    </html