apiVersion: apps/v1
kind: Deployment
metadata:
  name: otttuu-deployment
  namespace: testgmail-com
spec:
  selector:
    matchLabels:
      app: otttuu
  replicas: 1 
  template:
    metadata:
      labels:
        app: otttuu
    spec:
      containers:
      - name: otttuu
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: otttuu-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: otttuu-deployment
        configMap:
          name: otttuu-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: otttuu-service
  namespace: testgmail-com
spec:
  type: NodePort
  selector:
    app: otttuu
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: otttuu-deployment
  namespace: testgmail-com
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:teal;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa44efacc58bac164c9ec of user test@gmail.com</h1>
    </html