apiVersion: apps/v1
kind: Deployment
metadata:
  name: oklire-deployment
  namespace: testgmail-com
spec:
  selector:
    matchLabels:
      app: oklire
  replicas: 1 
  template:
    metadata:
      labels:
        app: oklire
    spec:
      containers:
      - name: oklire
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: oklire-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: oklire-deployment
        configMap:
          name: oklire-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: oklire-service
  namespace: testgmail-com
spec:
  type: NodePort
  selector:
    app: oklire
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: oklire-deployment
  namespace: testgmail-com
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:silver;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  629fa436facc58bac164c9ca of user test@gmail.com</h1>
    </html