apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpwjdy-deployment
  namespace: sashatest-ru
spec:
  selector:
    matchLabels:
      app: dpwjdy
  replicas: 1 
  template:
    metadata:
      labels:
        app: dpwjdy
    spec:
      containers:
      - name: dpwjdy
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: dpwjdy-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: dpwjdy-deployment
        configMap:
          name: dpwjdy-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: dpwjdy-service
  namespace: sashatest-ru
spec:
  type: NodePort
  selector:
    app: dpwjdy
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dpwjdy-deployment
  namespace: sashatest-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:navy;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  62bb6782d15f899fcf18b10c of user sasha@test.ru</h1>
    </html