apiVersion: apps/v1
kind: Deployment
metadata:
  name: lstoyw-deployment
  namespace: sashatest-ru
spec:
  selector:
    matchLabels:
      app: lstoyw
  replicas: 1 
  template:
    metadata:
      labels:
        app: lstoyw
    spec:
      containers:
      - name: lstoyw
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: lstoyw-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: lstoyw-deployment
        configMap:
          name: lstoyw-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: lstoyw-service
  namespace: sashatest-ru
spec:
  type: NodePort
  selector:
    app: lstoyw
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: lstoyw-deployment
  namespace: sashatest-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:olive;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  62bc474eda289c25b78ada45 of user sasha@test.ru</h1>
    </html