apiVersion: apps/v1
kind: Deployment
metadata:
  name: ukskdr-deployment
  namespace: vasiatest-ru
spec:
  selector:
    matchLabels:
      app: ukskdr
  replicas: 1 
  template:
    metadata:
      labels:
        app: ukskdr
    spec:
      containers:
      - name: ukskdr
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: ukskdr-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: ukskdr-deployment
        configMap:
          name: ukskdr-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: ukskdr-service
  namespace: vasiatest-ru
spec:
  type: NodePort
  selector:
    app: ukskdr
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ukskdr-deployment
  namespace: vasiatest-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:gray;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  62bd8a0d5fee01caa62b447d of user vasia@test.ru</h1>
    </html