apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdekoq-deployment
  namespace: sashatest-ru
spec:
  selector:
    matchLabels:
      app: rdekoq
  replicas: 1 
  template:
    metadata:
      labels:
        app: rdekoq
    spec:
      containers:
      - name: rdekoq
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: rdekoq-deployment
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: rdekoq-deployment
        configMap:
          name: rdekoq-deployment
---

kind: Service
apiVersion: v1
metadata:
  name: rdekoq-service
  namespace: sashatest-ru
spec:
  type: NodePort
  selector:
    app: rdekoq
  ports:
    - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rdekoq-deployment
  namespace: sashatest-ru
data:
  index.html: |
    <html>
    <style>
    html{
      background-color:green;
    }
    </style>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a conf  62cb228a01994ceffe76335e of user sasha@test.ru</h1>
    </html