apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-data
  namespace: consul
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/consul
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
