apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/jenkins
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
