apiVersion: v1
kind: Service
metadata:
  labels:
    app: bind
  name: bind-nodeport-svc
  namespace: bind
spec:
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
    nodePort: 32121
  selector:
    app: bind
  type: NodePort