apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
    release: mu-rabbit
  name: mu-rabbit-rabbitmq-nodeport
  namespace: rabbit
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: epmd
    nodePort: 32223
  - name: stats
    port: 15672
    protocol: TCP
    targetPort: stats
    nodePort: 32222
  - name: amqp
    nodePort: 32224
    port: 5672
    protocol: TCP
    targetPort: amqp
  selector:
    app: rabbitmq
    release: mu-rabbit
  sessionAffinity: None
  type: NodePort

